# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: How can I use Jekyll plug-ins?
email: yojyo@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-plugin-sandbox"
url: https://showa-yojyo.github.io
twitter_username: showa_yojyo
github_username: showa-yojyo

# Build settings
theme: minima
plugins:
  - jekyll-archives
  - jekyll-feed

minima:
  date_format: "%Y-%m-%d (%a)"
header_pages:
  - about.md
  - archive.html

lang: ja

repository: https://github.com/showa-yojyo/jekyll-plugin-sandbox
rss: Feed
show_excerpts: true

kramdown:
  remove_line_breaks_for_cjk: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Archives

jekyll-archives:
  enabled:
    - year
  layouts:
    year: year-archive
  permalinks:
    year: '/archive/:year/'
    category: '/category/:name/'

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      author: "showa-yojyo"
      categories:
        - diary
      layout: post
